name: Pages

on:
  push:
    branches: [ develop ]
    paths:
      - "mkdocs.yml"
      - "docs/**"
  pull_request:
    branches: [ develop ]
    paths:
      - "mkdocs.yml"
      - "docs/**"

jobs:
  pages:

    name: Pages
    runs-on: ubuntu-latest

    env:
      PYTHON_VER: "3.11"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ env.PYTHON_VER }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VER }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install mkdocs-material

    - name: Build and Publish
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        mkdocs build --strict
        mkdocs gh-deploy --force
