name: Pages

on:
  push:
    branches: [develop]
    paths:
      - "mkdocs.yml"
      - "docs/**"
      - "aiotieba_reviewer/__version__.py"
      - ".github/workflows/Pages*"
  pull_request:
    branches: [develop]
    paths:
      - "mkdocs.yml"
      - "docs/**"
      - "aiotieba_reviewer/__version__.py"
      - ".github/workflows/Pages*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VER: "3.11"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}

      - name: Install dependencies
        run: |
          pip install -U pip -qq
          pip install mkdocs-material -qq

      - name: Build
        run: |
          mkdocs build -d _site -s -q

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
