name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    environment:
       name: publish

    env:
      PYTHON_VER: "3.11"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VER }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VER }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip -qq
        pip install -U wheel build setuptools twine -qq

    - name: Build Package
      run: python -m build

    - name: Publish to PyPI
      run: twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} --disable-progress-bar
