name: Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  publish:
    name: Publish
    needs: build_sdist
    runs-on: ubuntu-latest

    environment:
      name: pypi

    permissions:
      id-token: write

    steps:
      - name: Download distributions
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish to PyPI
        if: ${{ github.event_name == 'push' }}
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to TestPyPI
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
